/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.init.PotionTypes
 *  net.minecraft.item.Item
 *  net.minecraft.item.ItemStack
 *  net.minecraft.item.crafting.IRecipe
 *  net.minecraft.potion.PotionType
 *  net.minecraft.potion.PotionUtils
 *  net.minecraft.util.ResourceLocation
 *  net.minecraftforge.registries.IForgeRegistry
 *  net.minecraftforge.registries.IForgeRegistryEntry
 *  thaumcraft.api.ThaumcraftApi
 *  thaumcraft.api.ThaumcraftApiHelper
 *  thaumcraft.api.aspects.Aspect
 *  thaumcraft.api.aspects.AspectList
 *  thaumcraft.api.blocks.BlocksTC
 *  thaumcraft.api.crafting.InfusionRecipe
 *  thaumcraft.api.items.ItemsTC
 *  vazkii.botania.common.item.ModItems
 */
package com.forgottenrelics.forgotten_relics.recipes;

import com.forgottenrelics.forgotten_relics.proxy.CommonProxy;
import com.forgottenrelics.forgotten_relics.recipes.RecipeOblivionStone;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.init.PotionTypes;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.item.crafting.IRecipe;
import net.minecraft.potion.PotionType;
import net.minecraft.potion.PotionUtils;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.registries.IForgeRegistry;
import net.minecraftforge.registries.IForgeRegistryEntry;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.ThaumcraftApiHelper;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.api.blocks.BlocksTC;
import thaumcraft.api.crafting.InfusionRecipe;
import thaumcraft.api.items.ItemsTC;
import vazkii.botania.common.item.ModItems;

public class FRRecipes {
    public static void initRecipes(IForgeRegistry<IRecipe> forgeRegistry) {
        FRRecipes.initInfusionRecipes();
        FRRecipes.initNormalRecipes(forgeRegistry);
    }

    private static void initInfusionRecipes() {
        Ingredient curioAny = Ingredient.fromStacks(new ItemStack(ItemsTC.curio, 1, 0), new ItemStack(ItemsTC.curio, 1, 1), new ItemStack(ItemsTC.curio, 1, 2), new ItemStack(ItemsTC.curio, 1, 3), new ItemStack(ItemsTC.curio, 1, 4), new ItemStack(ItemsTC.curio, 1, 5));
        Ingredient pearlAny = Ingredient.fromStacks(new ItemStack(ItemsTC.primordialPearl, 1, 0), new ItemStack(ItemsTC.primordialPearl, 1, 1), new ItemStack(ItemsTC.primordialPearl, 1, 2), new ItemStack(ItemsTC.primordialPearl, 1, 3), new ItemStack(ItemsTC.primordialPearl, 1, 4), new ItemStack(ItemsTC.primordialPearl, 1, 5), new ItemStack(ItemsTC.primordialPearl, 1, 6), new ItemStack(ItemsTC.primordialPearl, 1, 7));

        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "terror_crown"), (InfusionRecipe)new InfusionRecipe("TERROR_CROWN", (Object)new ItemStack((Item)CommonProxy.terrorCrown), 10, new AspectList().add(Aspect.ELDRITCH, 75).add(Aspect.MOTION, 75).add(Aspect.MAGIC, 175).add(Aspect.DARKNESS, 30).add(Aspect.VOID, 30), (Object)ItemsTC.goggles, new Object[]{Items.NETHER_STAR, "runePrideB", "ingotGold", "eternalLifeEssence", Items.ENDER_EYE, "eternalLifeEssence", "ingotGold", "runeWrathB"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "superposition_ring"), (InfusionRecipe)new InfusionRecipe("RING_OF_SUPERPOSITION", (Object)new ItemStack((Item)CommonProxy.superpositionRing), 4, new AspectList().add(Aspect.ELDRITCH, 125).add(Aspect.EXCHANGE, 100).add(Aspect.MOTION, 75).add(Aspect.DARKNESS, 75).add(Aspect.PROTECT, 30), (Object)new ItemStack(ItemsTC.baubles, 1, 1), new Object[]{Items.ENDER_EYE, new ItemStack(ModItems.manaResource, 1, 15), ItemsTC.voidSeed, ItemsTC.salisMundus, "gemEmerald", ItemsTC.salisMundus, ItemsTC.voidSeed, new ItemStack(ModItems.manaResource, 1, 15)}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "weather_stone"), (InfusionRecipe)new InfusionRecipe("WEATHER_STONE", (Object)new ItemStack((Item)CommonProxy.weatherStone), 4, new AspectList().add(Aspect.MOTION, 65).add(Aspect.AIR, 85).add(Aspect.WATER, 35).add(Aspect.EXCHANGE, 30).add(Aspect.ENERGY, 75), (Object)BlocksTC.stoneArcane, new Object[]{"eternalLifeEssence", Items.GHAST_TEAR, "runeAirB", new ItemStack(ItemsTC.celestialNotes, 1, 0), "nitor", new ItemStack(ItemsTC.celestialNotes, 1, 5), "runeAirB", Items.GHAST_TEAR}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "mining_charm"), (InfusionRecipe)new InfusionRecipe("MINING_CHARM", (Object)new ItemStack((Item)CommonProxy.MiningCharm), 1, new AspectList().add(Aspect.TOOL, 200).add(Aspect.MOTION, 200).add(Aspect.METAL, 175).add(Aspect.MAGIC, 200), (Object)ModItems.reachRing, new Object[]{ItemsTC.elementalPick, ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.EARTH), ItemsTC.salisMundus, "ingotGold", PotionUtils.addPotionToItemStack((ItemStack)new ItemStack((Item)Items.POTIONITEM), (PotionType)PotionTypes.LONG_SWIFTNESS), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.EARTH), ItemsTC.salisMundus, "ingotGold"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "dimensional_mirror"), (InfusionRecipe)new InfusionRecipe("DIMENSIONAL_MIRROR", (Object)new ItemStack((Item)CommonProxy.dimensionalMirror), 6, new AspectList().add(Aspect.MOTION, 150).add(Aspect.DARKNESS, 20).add(Aspect.MAGIC, 100).add(Aspect.VOID, 200).add(Aspect.ELDRITCH, 10), (Object)ItemsTC.handMirror, new Object[]{"eternalLifeEssence", new ItemStack(Blocks.GLOWSTONE), "elvenDragonstone", new ItemStack(ModItems.manaResource, 1, 15), ItemsTC.focus2, new ItemStack(ModItems.manaResource, 1, 15), "elvenDragonstone", new ItemStack(Blocks.GLOWSTONE)}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "advanced_mining_charm"), (InfusionRecipe)new InfusionRecipe("ADVANCED_MINING_CHARM", (Object)new ItemStack((Item)CommonProxy.AdvancedMiningCharm), 8, new AspectList().add(Aspect.TOOL, 250).add(Aspect.AURA, 150).add(Aspect.CRYSTAL, 185).add(Aspect.EXCHANGE, 150).add(Aspect.MOTION, 125).add(Aspect.MAGIC, 140).add(Aspect.TOOL, 175), (Object)new ItemStack((Item)CommonProxy.MiningCharm), new Object[]{ItemsTC.visResonator, ItemsTC.crystalEssence, "ingotElvenElementium", "elvenDragonstone", "eternalLifeEssence", ItemsTC.crystalEssence, ItemsTC.voidPick, ItemsTC.crystalEssence, "eternalLifeEssence", "elvenDragonstone", "ingotElvenElementium", ItemsTC.crystalEssence}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "ancient_aegis"), (InfusionRecipe)new InfusionRecipe("ANCIENT_AEGIS", (Object)new ItemStack((Item)CommonProxy.AncientAegis), 5, new AspectList().add(Aspect.PROTECT, 175).add(Aspect.EXCHANGE, 125).add(Aspect.LIFE, 100).add(Aspect.MAGIC, 30).add(Aspect.METAL, 20), (Object)new ItemStack(ItemsTC.baubles, 1, 6), new Object[]{"elvenDragonstone", PotionUtils.addPotionToItemStack((ItemStack)new ItemStack((Item)Items.POTIONITEM), (PotionType)PotionTypes.STRONG_HEALING), "ingotGold", ItemsTC.fabric, ModItems.knockbackBelt, ItemsTC.fabric, "ingotGold", PotionUtils.addPotionToItemStack((ItemStack)new ItemStack((Item)Items.POTIONITEM), (PotionType)PotionTypes.STRONG_HEALING)}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "dark_sun_ring"), (InfusionRecipe)new InfusionRecipe("DARK_SUN_RING", (Object)new ItemStack((Item)CommonProxy.darkSunRing), 8, new AspectList().add(Aspect.FIRE, 200).add(Aspect.PROTECT, 185).add(Aspect.EXCHANGE, 140).add(Aspect.DARKNESS, 150).add(Aspect.MAGIC, 100), (Object)new ItemStack(ItemsTC.baubles, 1, 5), new Object[]{ModItems.superLavaPendant, "ingotElvenElementium", Items.BLAZE_ROD, new ItemStack(BlocksTC.cinderpearl), ItemsTC.voidSeed, "nitor", ItemsTC.voidSeed, new ItemStack(BlocksTC.cinderpearl), Items.BLAZE_ROD, "ingotElvenElementium"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "deific_amulet"), (InfusionRecipe)new InfusionRecipe("DEIFIC_AMULET", (Object)new ItemStack((Item)CommonProxy.DeificAmulet), 4, new AspectList().add(Aspect.MAN, 125).add(Aspect.LIGHT, 165).add(Aspect.AURA, 200).add(Aspect.MAGIC, 100).add(Aspect.LIFE, 30).add(Aspect.EXCHANGE, 20), (Object)new ItemStack(ItemsTC.baubles, 1, 4), new Object[]{ModItems.lavaPendant, "eternalLifeEssence", "elvenPixieDust", "eternalLifeEssence", ItemsTC.visResonator, "eternalLifeEssence", "elvenPixieDust", "eternalLifeEssence"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "chaos_core"), (InfusionRecipe)new InfusionRecipe("CHAOS_CORE", (Object)new ItemStack((Item)CommonProxy.chaosCore), 10, new AspectList().add(Aspect.ENTROPY, 100).add(Aspect.ORDER, 100).add(Aspect.EXCHANGE, 200).add(Aspect.MAGIC, 125), (Object)ItemsTC.visResonator, new Object[]{"elvenDragonstone", "elvenPixieDust", "ingotVoid", "elvenPixieDust", ItemsTC.alumentum, "elvenPixieDust", "ingotVoid", "elvenPixieDust"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "paradox"), (InfusionRecipe)new InfusionRecipe("PARADOX", (Object)new ItemStack((Item)CommonProxy.paradox), 32, new AspectList().add(Aspect.AIR, 250).add(Aspect.FIRE, 250).add(Aspect.WATER, 250).add(Aspect.EARTH, 250).add(Aspect.ORDER, 250).add(Aspect.ENTROPY, 250).add(Aspect.VOID, 185).add(Aspect.AVERSION, 125).add(Aspect.MAGIC, 100).add(Aspect.EXCHANGE, 140), (Object)ItemsTC.voidSword, new Object[]{new ItemStack((Item)CommonProxy.chaosCore), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.AIR), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.FIRE), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.WATER), pearlAny, ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.EARTH), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.ORDER), ThaumcraftApiHelper.makeCrystal((Aspect)Aspect.ENTROPY)}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "shiny_stone"), (InfusionRecipe)new InfusionRecipe("SHINY_STONE", (Object)new ItemStack((Item)CommonProxy.shinyStone), 8, new AspectList().add(Aspect.LIFE, 375).add(Aspect.TRAP, 100).add(Aspect.EXCHANGE, 100).add(Aspect.MAGIC, 100).add(Aspect.CRYSTAL, 200), (Object)"elvenDragonstone", new Object[]{ItemsTC.visResonator, "ingotGold", "eternalLifeEssence", "nitor", new ItemStack(Items.GOLDEN_APPLE, 1, 1), "nitor", "eternalLifeEssence", "ingotGold"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "oblivion_amulet"), (InfusionRecipe)new InfusionRecipe("OBLIVION_AMULET", (Object)new ItemStack((Item)CommonProxy.oblivionAmulet), 16, new AspectList().add(Aspect.DEATH, 250).add(Aspect.EXCHANGE, 175).add(Aspect.VOID, 300).add(Aspect.DARKNESS, 100).add(Aspect.ELDRITCH, 100).add(Aspect.MAGIC, 125).add(Aspect.FIRE, 200), (Object)new ItemStack(ModItems.bloodPendant, 1, 0), new Object[]{Items.NETHER_STAR, Items.BLAZE_POWDER, "ingotVoid", Items.BLAZE_POWDER, ItemsTC.charmVoidseer, Items.BLAZE_POWDER, "ingotVoid", Items.BLAZE_POWDER}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "xp_tome"), (InfusionRecipe)new InfusionRecipe("EXPERIENCE_TOME", (Object)new ItemStack((Item)CommonProxy.XPTome), 4, new AspectList().add(Aspect.SOUL, 125).add(Aspect.MIND, 150).add(Aspect.EXCHANGE, 30).add(Aspect.MAGIC, 100), (Object)Items.WRITABLE_BOOK, new Object[]{new ItemStack(BlocksTC.jarBrain), ItemsTC.salisMundus, ItemsTC.amber, ItemsTC.salisMundus, "nitor", ItemsTC.salisMundus, ItemsTC.amber, ItemsTC.salisMundus}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "arcanum"), (InfusionRecipe)new InfusionRecipe("FR_ARCANUM", (Object)new ItemStack((Item)CommonProxy.arcanum), 12, new AspectList().add(Aspect.AURA, 80).add(Aspect.MAGIC, 500).add(Aspect.VOID, 125).add(Aspect.ELDRITCH, 175).add(Aspect.DARKNESS, 150).add(Aspect.MOTION, 100).add(Aspect.EXCHANGE, 185), (Object)pearlAny, new Object[]{new ItemStack(ItemsTC.amuletVis, 1, 1), ItemsTC.crystalEssence, "eternalLifeEssence", "ingotThaumium", new ItemStack(ModItems.manaResource, 1, 15), ItemsTC.crystalEssence, new ItemStack((Item)CommonProxy.superpositionRing), ItemsTC.crystalEssence, new ItemStack(ModItems.manaResource, 1, 15), "ingotThaumium", "eternalLifeEssence", ItemsTC.crystalEssence}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "oblivion_stone"), (InfusionRecipe)new InfusionRecipe("OBLIVION_STONE", (Object)new ItemStack((Item)CommonProxy.oblivionStone), 4, new AspectList().add(Aspect.VOID, 75).add(Aspect.DARKNESS, 75).add(Aspect.ENTROPY, 60).add(Aspect.EXCHANGE, 30).add(Aspect.MAGIC, 30), (Object)ItemsTC.charmVoidseer, new Object[]{Items.ENDER_EYE, ItemsTC.voidSeed, "ingotVoid", ItemsTC.voidSeed, "nitor", ItemsTC.voidSeed, "ingotVoid", ItemsTC.voidSeed}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "pech_wand_fr"), (InfusionRecipe)new InfusionRecipe("PECH_WAND_FR", (Object)new ItemStack(ItemsTC.pechWand), 5, new AspectList().add(Aspect.ENTROPY, 30).add(Aspect.EXCHANGE, 60).add(Aspect.MAGIC, 50).add(Aspect.SENSES, 30).add(Aspect.DEATH, 55), (Object)"stickWood", new Object[]{"gemEmerald", Items.BLAZE_POWDER, Items.GHAST_TEAR, Items.SUGAR, "gemQuartz", "gemQuartz", "gemQuartz", "dustRedstone", Items.NETHER_WART, Items.FERMENTED_SPIDER_EYE}));

        // Spellbook infusion recipes
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "tome_of_discord"), (InfusionRecipe)new InfusionRecipe("TOME_OF_DISCORD", (Object)new ItemStack((Item)CommonProxy.tomeOfDiscord), 5, new AspectList().add(Aspect.MOTION, 50).add(Aspect.DARKNESS, 30).add(Aspect.VOID, 30).add(Aspect.MAGIC, 45).add(Aspect.MIND, 24), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, "ingotElvenElementium", Items.ENDER_PEARL, new ItemStack(ModItems.manaResource, 1, 15), ItemsTC.salisMundus, ItemsTC.focus2, ItemsTC.salisMundus, new ItemStack(ModItems.manaResource, 1, 15), Items.ENDER_PEARL, "ingotElvenElementium"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "tome_of_broken_fates"), (InfusionRecipe)new InfusionRecipe("TOME_OF_BROKEN_FATES", (Object)new ItemStack((Item)CommonProxy.tomeOfBrokenFates), 20, new AspectList().add(Aspect.LIFE, 64).add(Aspect.EXCHANGE, 32).add(Aspect.MAN, 24).add(Aspect.MIND, 16).add(Aspect.SOUL, 36).add(Aspect.ORDER, 20).add(Aspect.MAGIC, 40), (Object)Items.WRITABLE_BOOK, new Object[]{new ItemStack(ModItems.manaResource, 1, 4), "elvenDragonstone", "eternalLifeEssence", "nitor", "eternalLifeEssence", ItemsTC.salisMundus, ItemsTC.visResonator, ItemsTC.salisMundus, "eternalLifeEssence", "nitor", "eternalLifeEssence", "elvenDragonstone"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "thunderpeal"), (InfusionRecipe)new InfusionRecipe("THUNDERPEAL", (Object)new ItemStack((Item)CommonProxy.thunderpeal), 4, new AspectList().add(Aspect.ENERGY, 32).add(Aspect.MAGIC, 24).add(Aspect.AIR, 24).add(Aspect.MIND, 10).add(Aspect.FIRE, 16), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, "elvenPixieDust", new ItemStack(ModItems.manaResource, 1, 1), ItemsTC.salisMundus, ItemsTC.focus1, ItemsTC.salisMundus, new ItemStack(ModItems.manaResource, 1, 1), "elvenPixieDust"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "tome_of_predestiny"), (InfusionRecipe)new InfusionRecipe("TOME_OF_PREDESTINY", (Object)new ItemStack((Item)CommonProxy.tomeOfPredestiny), 8, new AspectList().add(Aspect.MOTION, 32).add(Aspect.TRAP, 48).add(Aspect.MAGIC, 64).add(Aspect.DARKNESS, 24).add(Aspect.AIR, 25).add(Aspect.ENERGY, 40).add(Aspect.TOOL, 16), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, ItemsTC.voidSeed, ItemsTC.focus1, "eternalLifeEssence", ItemsTC.salisMundus, ModItems.gravityRod, ItemsTC.salisMundus, "eternalLifeEssence", ItemsTC.focus1, ItemsTC.voidSeed}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "edict_of_banishment"), (InfusionRecipe)new InfusionRecipe("EDICT_OF_BANISHMENT", (Object)new ItemStack((Item)CommonProxy.edictOfBanishment), 8, new AspectList().add(Aspect.FIRE, 70).add(Aspect.MOTION, 40).add(Aspect.MAGIC, 36).add(Aspect.MIND, 24).add(Aspect.DARKNESS, 48), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, Items.BLAZE_POWDER, Items.NETHERBRICK, ItemsTC.salisMundus, Items.NETHER_WART, Items.ENDER_EYE, Items.NETHER_WART, ItemsTC.salisMundus, Items.NETHERBRICK, Items.BLAZE_POWDER}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "devourer_of_the_void"), (InfusionRecipe)new InfusionRecipe("DEVOURER_OF_THE_VOID", (Object)new ItemStack((Item)CommonProxy.devourerOfTheVoid), 8, new AspectList().add(Aspect.ELDRITCH, 72).add(Aspect.VOID, 64).add(Aspect.DARKNESS, 64).add(Aspect.ENERGY, 40).add(Aspect.MAGIC, 52).add(Aspect.AURA, 25).add(Aspect.EXCHANGE, 32), (Object)Items.WRITABLE_BOOK, new Object[]{"nitor", curioAny, "ingotVoid", ItemsTC.visResonator, ItemsTC.fabric, ItemsTC.salisMundus, ItemsTC.causalityCollapser, ItemsTC.salisMundus, ItemsTC.fabric, ItemsTC.visResonator, "ingotVoid", curioAny}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "eldritch_spell"), (InfusionRecipe)new InfusionRecipe("ELDRITCH_SPELL", (Object)new ItemStack((Item)CommonProxy.eldritchSpell), 8, new AspectList().add(Aspect.ELDRITCH, 72).add(Aspect.DARKNESS, 64).add(Aspect.DEATH, 40).add(Aspect.MAGIC, 36).add(Aspect.MIND, 24).add(Aspect.TOOL, 12).add(Aspect.FLUX, 24), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, "ingotVoid", Items.FIRE_CHARGE, ItemsTC.causalityCollapser, ItemsTC.bottleTaint, ItemsTC.salisMundus, "eternalLifeEssence", ItemsTC.salisMundus, ItemsTC.bottleTaint, ItemsTC.causalityCollapser, Items.FIRE_CHARGE, "ingotVoid"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "crimson_spell"), (InfusionRecipe)new InfusionRecipe("CRIMSON_SPELL", (Object)new ItemStack((Item)CommonProxy.crimsonSpell), 8, new AspectList().add(Aspect.FIRE, 72).add(Aspect.ENTROPY, 64).add(Aspect.MAGIC, 54).add(Aspect.EXCHANGE, 24).add(Aspect.SENSES, 32).add(Aspect.MIND, 24).add(Aspect.ENERGY, 48), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.causalityCollapser, Items.BLAZE_POWDER, ItemsTC.fabric, ItemsTC.visResonator, Items.REDSTONE, ItemsTC.salisMundus, ItemsTC.causalityCollapser, ItemsTC.salisMundus, Items.REDSTONE, ItemsTC.visResonator, ItemsTC.fabric, Items.BLAZE_POWDER}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "tome_of_primal_chaos"), (InfusionRecipe)new InfusionRecipe("TOME_OF_PRIMAL_CHAOS", (Object)new ItemStack((Item)CommonProxy.tomeOfPrimalChaos), 12, new AspectList().add(Aspect.AIR, 100).add(Aspect.WATER, 100).add(Aspect.EARTH, 100).add(Aspect.FIRE, 100).add(Aspect.ORDER, 100).add(Aspect.ENTROPY, 100).add(Aspect.MAGIC, 256).add(Aspect.EXCHANGE, 72).add(Aspect.ELDRITCH, 36).add(Aspect.DARKNESS, 40), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.focus1, ItemsTC.salisMundus, "ingotElvenElementium", ItemsTC.focus1, "eternalLifeEssence", ItemsTC.salisMundus, ItemsTC.focus1, ItemsTC.salisMundus, "eternalLifeEssence", ItemsTC.focus1, "ingotElvenElementium", ItemsTC.salisMundus}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "nuclear_fury"), (InfusionRecipe)new InfusionRecipe("NUCLEAR_FURY", (Object)new ItemStack((Item)CommonProxy.nuclearFury), 10, new AspectList().add(Aspect.LIGHT, 72).add(Aspect.FIRE, 80).add(Aspect.ENTROPY, 36).add(Aspect.MAGIC, 64).add(Aspect.AURA, 16).add(Aspect.ENERGY, 48).add(Aspect.SENSES, 32).add(Aspect.VOID, 40), (Object)new ItemStack((Item)CommonProxy.tomeOfPrimalChaos), new Object[]{ModItems.missileRod, ItemsTC.alumentum, "ingotTerrasteel", ItemsTC.visResonator, "eternalLifeEssence", ItemsTC.crystalEssence, pearlAny, ItemsTC.crystalEssence, "eternalLifeEssence", ItemsTC.visResonator, "ingotTerrasteel", ItemsTC.alumentum}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "soul_tome"), (InfusionRecipe)new InfusionRecipe("SOUL_TOME", (Object)new ItemStack((Item)CommonProxy.soulTome), 10, new AspectList().add(Aspect.SOUL, 80).add(Aspect.VOID, 60).add(Aspect.MAGIC, 45).add(Aspect.TRAP, 60).add(Aspect.DEATH, 32).add(Aspect.DARKNESS, 48).add(Aspect.EXCHANGE, 52), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.pechWand, ItemsTC.alumentum, "eternalLifeEssence", Items.ENDER_EYE, "eternalLifeEssence", ItemsTC.salisMundus, new ItemStack(BlocksTC.jarBrain), ItemsTC.salisMundus, "eternalLifeEssence", Items.ENDER_EYE, "eternalLifeEssence", ItemsTC.alumentum}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "tome_of_lunar_flares"), (InfusionRecipe)new InfusionRecipe("TOME_OF_LUNAR_FLARES", (Object)new ItemStack((Item)CommonProxy.tomeOfLunarFlares), 12, new AspectList().add(Aspect.AIR, 64).add(Aspect.ENERGY, 96).add(Aspect.MAGIC, 120).add(Aspect.MIND, 32).add(Aspect.ORDER, 40).add(Aspect.MOTION, 16).add(Aspect.TOOL, 24).add(Aspect.LIGHT, 48), (Object)Items.WRITABLE_BOOK, new Object[]{ItemsTC.visResonator, new ItemStack(ModItems.manaResource, 1, 15), "ingotTerrasteel", ModItems.starSword, "eternalLifeEssence", ItemsTC.salisMundus, pearlAny, ItemsTC.salisMundus, "eternalLifeEssence", ModItems.starSword, "ingotTerrasteel", new ItemStack(ModItems.manaResource, 1, 15)}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "apotheosis"), (InfusionRecipe)new InfusionRecipe("APOTHEOSIS", (Object)new ItemStack((Item)CommonProxy.apotheosis), 48, new AspectList().add(Aspect.TOOL, 128).add(Aspect.TOOL, 72).add(Aspect.EXCHANGE, 54).add(Aspect.MAGIC, 80).add(Aspect.LIGHT, 64).add(Aspect.METAL, 32).add(Aspect.MIND, 48).add(Aspect.ORDER, 40), (Object)Items.WRITABLE_BOOK, new Object[]{ModItems.kingKey, curioAny, "ingotGold", ItemsTC.visResonator, "eternalLifeEssence", ItemsTC.salisMundus, pearlAny, ItemsTC.salisMundus, "eternalLifeEssence", ItemsTC.visResonator, "ingotGold", curioAny}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "false_justice"), (InfusionRecipe)new InfusionRecipe("FALSE_JUSTICE", (Object)new ItemStack((Item)CommonProxy.falseJustice), 24, new AspectList().add(Aspect.LIGHT, 120).add(Aspect.AVERSION, 24).add(Aspect.TOOL, 40).add(Aspect.TOOL, 36).add(Aspect.MAN, 52).add(Aspect.MAGIC, 36).add(Aspect.EXCHANGE, 72).add(Aspect.SOUL, 48).add(Aspect.DARKNESS, 45), (Object)Items.WRITABLE_BOOK, new Object[]{"nitor", "ingotGold", Items.NETHER_STAR, curioAny, pearlAny, curioAny, Items.NETHER_STAR, "ingotGold"}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "void_grimoire"), (InfusionRecipe)new InfusionRecipe("VOID_GRIMOIRE", (Object)new ItemStack((Item)CommonProxy.voidGrimoire), 10, new AspectList().add(Aspect.VOID, 100).add(Aspect.DARKNESS, 52).add(Aspect.MOTION, 24).add(Aspect.MAGIC, 40).add(Aspect.MIND, 32).add(Aspect.ELDRITCH, 40).add(Aspect.EXCHANGE, 16).add(Aspect.ENTROPY, 20), (Object)new ItemStack((Item)CommonProxy.edictOfBanishment), new Object[]{"eternalLifeEssence", ItemsTC.voidSeed, curioAny, ItemsTC.voidSeed, ItemsTC.causalityCollapser, ItemsTC.voidSeed, curioAny, ItemsTC.voidSeed}));
        ThaumcraftApi.addInfusionCraftingRecipe((ResourceLocation)new ResourceLocation("forgotten_relics", "discord_ring"), (InfusionRecipe)new InfusionRecipe("DISCORD_RING", (Object)new ItemStack((Item)CommonProxy.ringOfDiscord), 2, new AspectList().add(Aspect.TOOL, 16).add(Aspect.MOTION, 16).add(Aspect.MAGIC, 12).add(Aspect.EXCHANGE, 8).add(Aspect.VOID, 8), (Object)new ItemStack(ItemsTC.baubles, 1, 1), new Object[]{"elvenDragonstone", ItemsTC.salisMundus, "ingotElvenElementium", ItemsTC.salisMundus, "eternalLifeEssence", ItemsTC.salisMundus, "ingotElvenElementium", ItemsTC.salisMundus}));
    }

    private static void initNormalRecipes(IForgeRegistry<IRecipe> forgeRegistry) {
        forgeRegistry.register(new RecipeOblivionStone());
    }
}

